### ISSUE TITLE
do 语法不太 js

### ISSUE THREAD

**Issue by cuixiping** [dlight-js/dlight#1]
挺用心的一个框架!
瞅了一眼中文文档, 也还算细致. 这个 jsd 替代 jsx 让人舒适.

提一点小意见, do 语法不太 js 啊, 在这里显得另类.

```
Body() {
  div {
    _(!console.log("expression just like you used to write") && "display this sentence")
    _(this.show && do {
      div("will show if this.show is true")
    })
  }
}
```

**Comment by IanDxSSXX** [comment]
这里可能文档没有更新，现在是没有domain syntax了，全都兼容了js语法，所以这一段现在的写法应该是：
Body() {
  div()
  {
    _(!console.log("expression just like you used to write") && "display this sentence")
    _(this.show && do {
      div("will show if this.show is true")
    })
  }
}
相当于div()是一个functionCall，下面的是一个blockStatement。
置于为什么要用do，是因为需要在_()中把普通函数调用和 div()这种dlight component区分开来，然而js不允许在prop里面直接添加block，只能通过 doExpression 也就是do{} 来把它识别出来（不然没法区分div()是一个component还是只是一个名字叫div的普通函数调用）。这个写法也是最近为了完全兼容js改的，因为js没有提供其他的写法（也可能有些偏门的我没找到），如果有啥好的建议也欢迎讨论呀

**Comment by cuixiping** [comment]
考虑到名称冲突的情况显然比不冲突的情况少, 那么是否可以考虑, 不冲突时智能识别, 冲突时给名称冲突的普通函数提供一个新的调用方式?

举个例子:

不冲突的时候,  `this.show && div("component")` 这里div是component
不冲突的时候,  `this.show && push("function")` 这里push是普通函数
冲突的时候,  `this.show && (div)("function") && div("component")` 这里第1个div是普通函数,第2个div是component

**Comment by IanDxSSXX** [comment]
> 考虑到名称冲突的情况显然比不冲突的情况少, 那么是否可以考虑, 不冲突时智能识别, 冲突时给名称冲突的普通函数提供一个新的调用方式?
> 
> 举个例子:
> 
> 不冲突的时候, `this.show && div("component")` 这里div是component 不冲突的时候, `this.show && push("function")` 这里push是普通函数 冲突的时候, `this.show && (div)("function") && div("component")` 这里第1个div是普通函数,第2个div是component

这种我也考虑过，但是有一个问题，因为这不像jsx只能返回一个jsxElement（多个要用空tag或者Fragment包吧）。jsd是自动收集block里面所有的element的，比如：
```js
Body() {
  div("1")
  div("2")
}
```
或者:
```js
div()
{
  div("sub1")
  div("sub2")
}
```
是嵌套解析的，放到_()的参数里面，如果用 do {}，那么也是符合嵌套解析，返回一个element array，但是如果是一个`this.show && div("component") ` 这种情况，就只有一个值了（对于返回一个值，一开始的尝试是直接外面包一层`this.show && _(div("component"))` 或者 `this.show &&  $(div("component"))`这样也不会有冲突。
最关键的问题还是js不能有单独的block {} 存在，只能通过 do {} 来绕过去。

**Comment by cuixiping** [comment]
单独block { } 有歧义, 这样看来, do 表达式也是不二之选.
