### ISSUE TITLE
component messasing system?

### ISSUE THREAD

**Issue by juanyacovino77** [dlight-js/dlight#33]
hey how would you pass messages between class component using dlight?

lets say a child component want to change state of another componer or a parent component... 

how would that be done?

**Comment by IanDxSSXX** [comment]
DLight of version 0.5.x has a two-way data flow, but we think that it's a little bit confusing and wir. So we change back to one-way data flow just like react, you can pass a `handleChange` function from the parent to the child just like this: 
```js
class ChildComp extends View {
  @Prop handleChange

  Body() {
    button("change")
      .onclick(handleChange)
  }
}

class ParentComp extends View {
  count = 0
 
  Body() {
    ChildComp()
      .handleChange(() => {
         this.count++
      })
   div(`now the count is ${this.count}`)
  }
}
```

**Comment by juanyacovino77** [comment]
Ok fine, there should be New object-oriented way of doing this.

And how you should suscribe for external event Using dlight components? At willMount()? For example if i want to listen to external service entries like websockets..?

**Comment by IanDxSSXX** [comment]
Not sure I understand that. Could you give me an example in React?

**Comment by juanyacovino77** [comment]
With React it would be done with useEffect for listening external events likes this:

How would you do the same with dlite?

`import React, { useState, useEffect } from "react";
import io from "socket.io-client";

const ChatRoom = () => {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([]);
  const [socket, setSocket] = useState(null);

  useEffect(() => {
    // connect to WebSocket server
    const newSocket = io("http://localhost:8080");
    setSocket(newSocket);

    // set up event listeners for incoming messages
    newSocket.on("connect", () => console.log("Connected to WebSocket"));
    newSocket.on("disconnect", () =>
      console.log("Disconnected from WebSocket")
    );
    newSocket.on("message", (data) => {
      setMessages((msgs) => [...msgs, data]);
    });

    // clean up on unmount
    return () => {
      newSocket.disconnect();
    };
  }, []);

  const handleSend = (e) => {
    e.preventDefault();
    if (message.trim() !== "") {
      // send message to WebSocket server
      socket.emit("message", message);
      setMessage("");
    }
  };

  return (
    <div>
      <h1>Chat Room</h1>
      <div>
        {messages.map((msg, index) => (
          <div key={index}>{msg}</div>
        ))}
      </div>
      <form onSubmit={handleSend}>
        <input
          type="text"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
        />
        <button type="submit">Send</button>
      </form>
    </div>
  );
};
export default ChatRoom;`
