### ISSUE TITLE
Missing some properties in `form` element on type level

### ISSUE THREAD

**Issue by scythewyvern** [dlight-js/dlight#66]
in `form` element from `'@dlightjs/types'` missing properties like `onSubmit`
but in fact these properties exist

so following code will fire 'submit' in console without page reload despite the type error:

```ts
form()
  .onSumbit((e) => {
    e.preventDefault()
    console.log('submit')
  })
```

dlight version:
```json
"dependencies": {
  "@dlightjs/dlight": "^1.0.0-alpha.65"
},

"devDependencies": {
  "@dlightjs/types": "^1.0.0-alpha.1"
},
```

**Comment by IanDxSSXX** [comment]
Fixed in the latest DLight version
