### ISSUE TITLE
Blank Page Displayed After Launching DLight.js Project

### ISSUE THREAD

**Issue by GrahLnn** [dlight-js/dlight#81]
Hi, I followed the quick start guide to install and launch dlight, but when I open it in the browser, all I see is a blank page. I'm not sure what went wrong. Is there any way to solve this issue? 

Thank you

![fdfecbaecbcf6a4e5046e188e2b4540e](https://github.com/dlight-js/dlight/assets/67181515/2b4e79d5-8719-461f-ab95-9f4d72e9e0ce)

**Comment by IanDxSSXX** [comment]
Can you provide the version of `@dlightjs/dlight` and `vite-plugin-dlight` and the error message? (BTW, join discord for quick support!)

**Comment by IanDxSSXX** [comment]
Ah yeah sorry, I just made a change to use `Body` intead of `View` to define the view but forgot to update the template. It should be fine now. Try to recreate the project

**Comment by GrahLnn** [comment]
Now it's working, thank you.
