### ISSUE TITLE
Feature: Add a ref prop to custom views

### ISSUE THREAD

**Issue by ansarizafar** [dlight-js/dlight#82]
If we want to access a view instance, then we can use lifecycle methods. This feature request suggests a shortcut for getting a view instance.
```javascript
    view().ref(this.el)
```

**Comment by IanDxSSXX** [comment]
Supported with https://github.com/dlight-js/dlight/commit/4abea674ac1da2810fb14df53ec6f1397c5e2852 and https://github.com/dlight-js/dlight/commit/ad18869ffdce2a76a802019b48aac5c71e741d30
