### ISSUE TITLE
input不支持readonly，option不支持selected

### ISSUE THREAD

**Issue by yuhengliang** [dlight-js/dlight#87]
input().readonly()
input().readonly(true)
input().readonly('readonly')
input不支持readonly，以上几个方法都不生效，请问该如何设置readonly？

select()
{
    option('0')
    option('1').selected()
    option('2').selected(true)
    option('3').selected('selected')
}
option不支持selected，以上几个方法都不生效，请问该如何设置selected？

**Comment by yuhengliang** [comment]
再次确认了一下selected 貌似是已经设置在option上，但dom中不显示。
但input的readonly确实不显示也不生效

**Comment by yuhengliang** [comment]
问题已经解决，✅正确的打开方式是：
                    input().readOnly()
                    input().readOnly(true)
                    input().readOnly('readonly')

**Comment by IanDxSSXX** [comment]
Yeah they should all be camelCased because they're in fact **properties** instead of **attributes**
